version: '3.9'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbfoyer
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app-foyer:
    image: louaysboui/tp-foyer:5.0.0
    container_name: app-foyer
    depends_on:
      - mysqldb
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/foyer_db?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": ,
        "spring.jpa.show-sql": "true",
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
        "spring.datasource.hikari.maximum-pool-size": "10",
        "spring.datasource.hikari.minimum-idle": "5",
        "spring.datasource.hikari.idle-timeout": "60000",
        "spring.datasource.hikari.connection-timeout": "30000",
        "spring.datasource.hikari.max-lifetime": "1800000",
        "server.port": "8089",
        "server.servlet.context-path": "/tpfoyer",
        "logging.level.org.springframework": "INFO",
        "logging.level.root": "INFO"
      }'

volumes:
  db_data: