version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0                 # MySQL version 8.0
    environment:
      MYSQL_DATABASE: foyerdb         # Database name
      MYSQL_ROOT_PASSWORD:  # Define the root password
    ports:
      - "3306:3306"                   # Expose MySQL port
    volumes:
      - mysql_data:/var/lib/mysql     # Persist MySQL data
    networks:
      - foyer-network                 # Custom network for communication

  # Spring Boot Application Service
  projet_final:
    container_name: projet_final
    image: louaysboui/tp-foyer:5.0.0  # Docker image name for Spring Boot app
    build: .
    depends_on:
      - mysql                         # Ensure MySQL starts before the app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/foyerdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword  # Match MySQL root password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_H2_CONSOLE_ENABLED: "true"
      SPRING_H2_CONSOLE_PATH: /h2-console
    ports:
      - "8082:8082"                   # Expose the Spring Boot application port
    networks:
      - foyer-network

volumes:
  mysql_data:                         # Named volume for MySQL persistence

networks:
  foyer-network:                      # Custom network to connect both containers
