version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: foyerdb
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - foyer-network

  # Spring Boot Application Service
  tp-foyer:
    image: louaysboui/tp-foyer:5.0.0
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/foyerdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: true
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: prometheus
    ports:
      - "8089:8089"
    networks:
      - foyer-network

  # Prometheus Service
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - foyer-network

  # Grafana Service
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - foyer-network

volumes:
  mysql_data:

networks:
  foyer-network:
